#!/bin/bash
sudo pacman -S haveged
sudo haveged -w 1024
sudo pacman-key --init && sudo pacman-key --populate archlinux
sudo pacman -Syy
sudo pkill haveged

#gnomex packages
sudo pacman -S gnome-shell gnome-shell-extensions gnome-control-center gnome-backgrounds gnome-tweak-tool thunar thunar-volman gvfs thunar-archive-plugin garcon tumbler ristretto xfce4-terminal leafpad mate-system-monitor ncdu parcellite xdg-user-dirs

#Network Services
sudo systemctl enable NetworkManager

#Enable the shell
touch .xinitrc
echo "exec gnome-session" > .xinitrc
