#!/bin/bash
sudo pacman -S haveged
sudo haveged -w 1024
sudo pacman-key --init && sudo pacman-key --populate archlinux
sudo pacman -Syy
sudo pkill haveged

#gnomex packages
sudo pacman -S epiphany numix-themes dosfstools ntfs-3g mate-icon-theme-faenza gnome-keyring gksu gnome-disk-utility gnome-shell gnome-shell-extensions gnome-control-center gnome-backgrounds gnome-tweak-tool thunar thunar-volman gvfs thunar-archive-plugin garcon tumbler ristretto xfce4-terminal leafpad mate-system-monitor ncdu parcellite xdg-user-dirs unrar unzip p7zip

#Network Services
sudo systemctl enable NetworkManager

#User folders
xdg-user-dirs-update

#Enable shell login
touch .xinitrc
echo "exec gnome-session" > .xinitrc

#AUR Install
chmod +x gnomex/aur_ins
gnomex/aur_ins

gsettings set org.gnome.desktop.interface gtk-theme Numix
gsettings set org.gnome.desktop.interface icon-theme matefaenzadark
gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/gnome/Stones.jpg'

