#!/bin/bash
sudo pacman -S haveged
sudo haveged -w 1024
sudo pacman-key --init && sudo pacman-key --populate archlinux
sudo pacman -Syy
sudo pkill haveged

#gnomex packages
sudo pacman -S epiphany gnome-keyring gksu gnome-shell gnome-shell-extensions gnome-control-center gnome-backgrounds gnome-tweak-tool thunar thunar-volman gvfs thunar-archive-plugin garcon tumbler ristretto xfce4-terminal leafpad mate-system-monitor ncdu parcellite xdg-user-dirs

#Network Services
sudo systemctl enable NetworkManager

#User folders
xdg-user-dirs-update

#Enable shell login
touch .xinitrc
echo "exec gnome-session" > .xinitrc

#AUR Install
chmod +x gnomex/aur_ins
gnomex/aur_ins
